[package]
name = "termsearch"
version = "0.1.0"
edition = "2024"

[dependencies]
crossterm = "0.28.1"
ratatui = "0.29.0"
reqwest = "0.12.12"
scraper = "0.23.1"
tokio = { version = "1", features = ["full"] }
webbrowser = "1.0.4"
